phrase:
  pull:
    targets:
    - file: ./Sources/UI/Resources/<locale_name>.lproj/Localizable.strings
      project_id: 907a05850acd3c14399a1d166db20d7a
      params:
        file_format: strings
        encoding: "UTF-8"
        fallback_locale_id: da12d11a9caeca774463f3c6e179ad20
        include_empty_translations: true
        format_options:
            convert_placeholder: true
            include_pluralized_keys: false
    - file: ./Sources/UI/Resources/<locale_name>.lproj/Localizable.stringsdict
      project_id: 907a05850acd3c14399a1d166db20d7a
      params:
        file_format: stringsdict
        encoding: "UTF-8"
        fallback_locale_id: da12d11a9caeca774463f3c6e179ad20
        include_empty_translations: true
        format_options:
            convert_placeholder: true

