on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer

name: Test
jobs:
  sdk:
    name: SDK
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set ImageVersion environment variable
        run: echo "ImageVersion=$ImageVersion"  >> $GITHUB_ENV

      - name: SPM Cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-${{ env.ImageVersion }}

      - name: Test
        run: xcodebuild test -scheme SnabblePay-Package -destination 'platform=iOS Simulator,name=iPhone 14' -sdk iphonesimulator